### ISSUE TITLE
Issue with /qsw command in paperspigot 1.13.1

### ISSUE THREAD

**Issue by astirling** [DNx5/QuickSellWand#1]
Server version: Paper version git-Paper-317 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
QSW version: QuickSellWand v1.0.2-SNAPSHOT

`[23:25:43] [Server thread/INFO]: Magarathin issued server command: /qsw give Magarathin 150
[23:25:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'qsw' in plugin QuickSellWand v1.0.2-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-317]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1769) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1573) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-317]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_65]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-317]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-317]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.IllegalArgumentException: ordinal on modern Material
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.1.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_13_R2.util.CraftLegacy.ordinal(CraftLegacy.java:233) ~[patched_1.13.1.jar:git-Paper-317]
	at co.aeria.quicksellwand.utils.CompatUtils.materialIsItem(CompatUtils.java:65) ~[?:?]
	at co.aeria.quicksellwand.service.WandService.getNewWand(WandService.java:53) ~[?:?]
	at co.aeria.quicksellwand.cmd.QuickSellWandCommand.onCommand(QuickSellWandCommand.java:44) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-317]
	... 15 more`

**Comment by DNx5** [comment]
did you put a valid material in the configuration?
the list materials for latest spigot is available at
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by astirling** [comment]
Yes, DIAMOND_HOE.  I've attached my config file.
[config.yml.txt](https://github.com/DNx5/QuickSellWand/files/2474954/config.yml.txt)
